POST http://localhost:4000/api/cities
Content-Type: application/json

{
  "name": "Lisbon",
  "country": "Portugal",
  "url": "/lisbon.jpeg",
  "flag": "PT",
  "history": "Lisbon, the capital of Portugal, has a long and storied history that dates back over two millennia. It was settled by Phoenicians, Greeks, and Carthaginians before becoming part of the Roman Empire. Throughout its history, Lisbon has been a center of trade, exploration, and culture. It played a crucial role in the Age of Discovery during the 15th and 16th centuries. Today, it retains its historic charm while embracing modernity.",
  "population": "Approximately 547,733",
  "weather": "Lisbon has a Mediterranean climate with mild, rainy winters and warm, dry summers. Average temperatures range from 8-15°C in winter and 18-28°C in summer."
}

PUT http://localhost:4000/api/cities/64dffcbf8916f350ae4e7580
Content-Type: application/json

{
  "url": "/sydney.jpg"
}

DELETE http://localhost:4000/api/city-itineraries/64efdb514b73b9a1b4b3bea1
Content-Type: application/json


POST http://localhost:4000/api/city-itineraries
Content-Type: application/json

{
  "cityId": "64dec82e56c6217793abce59",
  "itineraryName": "Beer's Factory Tour",
  "price":"4",
  "duration":"4 hour",
  "urlImage": "/itMDQ2.jpg",
  "profilePicture":"https://source.unsplash.com/80x80?face",
  "profileName":"G.Alvarez",
  "likes":"0",
  "hashtags":["#MDQBeer", "#AntaresBeer", "#AtlanticPearl"]
}

PUT http://localhost:4000/api/city-itineraries/64efe33f4b73b9a1b4b3beb8
Content-Type: application/json

{

  "urlImage": "/itPuntaCana2.jpg"

}